"""Column tamanho

Revision ID: 87a54b550568
Revises: 782f8fdedd72
Create Date: 2021-12-22 21:50:47.788574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a54b550568'
down_revision = '782f8fdedd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_produto_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_usuario', 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usuario', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_produto_id'))
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
